### ISSUE TITLE
getTransformResult error when installing nuxt 3

### ISSUE THREAD

**Issue by hasanbanna** [vue-macros/vue-macros#438]
```
 ERROR  The requested module '@vue-macros/common' does not provide an export named 'getTransformResult'     4:43:23 PM

  getTransformResult,
  ^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module '@vue-macros/common' does not provide an export named 'getTransformResult'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2536:37)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)

```

I am trying to install nuxt 3 via `npx nuxi@latest init` and I am getting this error? I am guessing this is an error on this dependency for nuxt 3. Happy to close this if not.

**Comment by sxzz** [comment]
Sorry for the bug, will fix it in minutes.
