### ISSUE TITLE
I got an build error when i use  `unplugin-vue-define-options@1.3.15`

### ISSUE THREAD

**Issue by 403NotFound** [vue-macros/vue-macros#462]
**node  14.21.1**
**vue 2.7.14**
**vite 4.4.5**

### Description
I want to use `unplugin-vue-define-options` to set my vue components name, i installed `unplugin-vue-define-options@1.3.15`,when i build my project with vite , i got an error:

js code:
```js
<script setup>
defineOptions({
  name: 'ZInput',
})

onMounted(() => {
  console.log('hello')
})
</script>
```

build error msg:
```
[unplugin-vue-define-options] scopeStack.at is not a function
file: /Users/zhanglei/Documents/ZYKWork/zyk/zykui/packages/components/input/src/index.vue
error during build:
TypeError: scopeStack.at is not a function
    at leaveNode (file:///Users/zhanglei/Documents/ZYKWork/zyk/zykui/node_modules/.pnpm/registry.npmmirror.com+ast-walker-scope@0.5.0/node_modules/ast-walker-scope/dist/index.mjs:180:33)
    at Object.leave (file:///Users/zhanglei/Documents/ZYKWork/zyk/zykui/node_modules/.pnpm/registry.npmmirror.com+ast-walker-scope@0.5.0/node_modules/ast-walker-scope/dist/index.mjs:120:9)
    at SyncWalker.visit (file:///Users/zhanglei/Documents/ZYKWork/zyk/zykui/node_modules/.pnpm/registry.npmmirror.com+ast-kit@0.9.5/node_modules/ast-kit/dist/index.js:428:20)
    at SyncWalker.visit (file:///Users/zhanglei/Documents/ZYKWork/zyk/zykui/node_modules/.pnpm/registry.npmmirror.com+ast-kit@0.9.5/node_modules/ast-kit/dist/index.js:413:27)
    at SyncWalker.visit (file:///Users/zhanglei/Documents/ZYKWork/zyk/zykui/node_modules/.pnpm/registry.npmmirror.com+ast-kit@0.9.5/node_modules/ast-kit/dist/index.js:419:18)
    at SyncWalker.visit (file:///Users/zhanglei/Documents/ZYKWork/zyk/zykui/node_modules/.pnpm/registry.npmmirror.com+ast-kit@0.9.5/node_modules/ast-kit/dist/index.js:413:27)
    at walk (file:///Users/zhanglei/Documents/ZYKWork/zyk/zykui/node_modules/.pnpm/registry.npmmirror.com+ast-kit@0.9.5/node_modules/ast-kit/dist/index.js:557:19)
    at walkAST (file:///Users/zhanglei/Documents/ZYKWork/zyk/zykui/node_modules/.pnpm/registry.npmmirror.com+ast-walker-scope@0.5.0/node_modules/ast-walker-scope/dist/index.mjs:105:3)
    at getRootScopeIds (file:///Users/zhanglei/Documents/ZYKWork/zyk/zykui/node_modules/.pnpm/registry.npmmirror.com+unplugin-vue-define-options@1.3.15_vue@2.7.14/node_modules/unplugin-vue-define-options/dist/chunk-6BKG7JEA.mjs:87:3)
    at transformDefineOptions (file:///Users/zhanglei/Documents/ZYKWork/zyk/zykui/node_modules/.pnpm/registry.npmmirror.com+unplugin-vue-define-options@1.3.15_vue@2.7.14/node_modules/unplugin-vue-define-options/dist/chunk-6BKG7JEA.mjs:45:25)
```
**Funnily enough，** **build success when i removed onMounted hook**
then, I reduce `unplugin-vue-define-options` version to `1.3.14`, build sucess when i use onMounted hook

Question is why 1.3.15 not work but 1.3.14 worked

Looking forward to receiving an answer

**Comment by sxzz** [comment]
The required Node version is Node.js 16.14.0 or higher. Please upgrade your node version.

**Comment by sxy15** [comment]
tks

**Comment by 1071125093** [comment]
mark
