### ISSUE TITLE
unplugin-vue-macros 2.4.9 leads to "Cannot set property parseSFC of #<Object> which has only a getter" error

### ISSUE THREAD

**Issue by davy-ikv** [vue-macros/vue-macros#475]
unplugin-vue-macros 2.4.9 will cause error with vite:

```
failed to load config from /path/to/project/vite.config.ts
error when starting dev server:
TypeError: Cannot set property parseSFC of #<Object> which has only a getter
    at Object.<anonymous> (/path/to/project/node_modules/@vue-macros/define-prop/node_modules/@vue-macros/api/dist/index.js:1596:848)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at _require.extensions.<computed> [as .js] (file:///path/to/project/node_modules/vite/dist/node/chunks/dep-df561101.js:66256:17)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/path/to/project/node_modules/@vue-macros/define-prop/dist/chunk-PPGAVW6K.js:8:12)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
```

**Comment by asakurayoh1987** [comment]
same error

**Comment by zhiyuanzmj** [comment]
I get It, You can remove `type: "module"` in package.json first.

**Comment by Miofly** [comment]
> I get It, You can add `type: "module"` in package.json first.

Why it must be added type: "module"

**Comment by JLXFeng** [comment]
> 

Is your problem still there？

**Comment by sxzz** [comment]
Can you provide a reproduction repo plz?

**Comment by LYlanfeng** [comment]
初步查询原因如下
```
var _common = require('@vue-macros/common')
_createStarExport(_common)
// 在这个地方导出了parseSFC方法，然后只设置了get
function _createStarExport(obj) {
  Object.keys(obj)
    .filter(key => key !== 'default' && key !== '__esModule')
    .forEach(key => {
      if (exports.hasOwnProperty(key)) {
        return
      }
      Object.defineProperty(exports, key, {
        enumerable: true,
        configurable: true,
        get: () => obj[key] // 只有get，没有set导致下面重复赋值错误
      })
    })
}

// 最下面 这个跟_createStarExport的方法冲突了，导致报错不能赋值，因为没有set
exports.parseSFC = _common.parseSFC

```

**Comment by sxzz** [comment]
Fixed, thanks for your feedbacks!
