### ISSUE TITLE
vite] Internal server error: At least one <template> or <script> is required in a single file component.

### ISSUE THREAD

**Issue by dspangenberg** [vue-macros/vue-macros#538]
### Describe the bug

After adding VueMacros({
      plugins: {
        vue: Vue(),
        // vueJsx: VueJsx(), // if needed
      },
    })

to vite.config.ts I get the following error:

[vite] Internal server error: At least one <template> or <script> is required in a single file component.
  Plugin: vite:vue
  File: /Users/dspangenberg/Projects/twiceware.cloud/bskytrails/src/views/HomeView.vue
      at Object.parse$2 [as parse] (/Users/dspangenberg/Projects/twiceware.cloud/bskytrails/node_modules/.pnpm/@vue+compiler-sfc@3.3.7/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:1905:7)
      at createDescriptor (/Users/dspangenberg/Projects/twiceware.cloud/bskytrails/node_modules/.pnpm/@vitejs+plugin-vue@4.4.0_vite@4.5.0_vue@3.3.7/node_modules/@vitejs/plugin-vue/dist/index.cjs:86:43)
      at transformMain (/Users/dspangenberg/Projects/twiceware.cloud/bskytrails/node_modules/.pnpm/@vitejs+plugin-vue@4.4.0_vite@4.5.0_vue@3.3.7/node_modules/@vitejs/plugin-vue/dist/index.cjs:2298:34)
      at TransformContext.transform (/Users/dspangenberg/Projects/twiceware.cloud/bskytrails/node_modules/.pnpm/@vitejs+plugin-vue@4.4.0_vite@4.5.0_vue@3.3.7/node_modules/@vitejs/plugin-vue/dist/index.cjs:2830:16)
      at Object.transform (file:///Users/dspangenberg/Projects/twiceware.cloud/bskytrails/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.8/node_modules/vite/dist/node/chun

### Reproduction

https://github.com/dspangenberg/vite-vue-marcros-bug

### System Info

```Shell
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1
    Memory: 112.34 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.7.2 - ~/Library/pnpm/npm
    pnpm: 8.6.5 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 108.1.46.153
    Chrome: 118.0.5993.88
    Safari: 16.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhiyuanzmj** [comment]
Please don't use the `Vue` plugin twice.
https://github.com/dspangenberg/vite-vue-marcros-bug/blob/main/vite.config.ts#L11

**Comment by dspangenberg** [comment]
Thank you!
